### PR TITLE
Reorganize package.js and remove unused deps

### PR DESCRIPTION
**Pull request by dting**
Removed a lot of unused dependencies and moved dev dependencies to the devDependencies section.

Renamed npm script "demo" to "dev"

To run the mongo server and webpack use:

```
npm run dev
```

### CODE REVIEW

**Comment by wayneadams** [comment]
does this incorporate pr's #6 & #7 ?

**Comment by dting** [comment]
This change is a child of the commits in those PRs. I've rebased to master since those PR's have been merged.

**Comment by wayneadams** [comment]
solid. makes sense and looks good to  me.

**Comment by dting** [comment]
Thanks!

**Pull request merged**
